import { type NextRequest, NextResponse } from "next/server";

const comedyPosts = [
  {
    id: 1,
    title: "Mening mushukimning kundalik hayoti",
    body: "Bugun mushugim yana meni soat 5 da uyg'otdi. Sababi? Uning idishi yarim bo'sh edi! Tabiiyki, bu dunyoning oxiri edi uning fikriga ko'ra. Keyin esa butun kun davomida uxlab yotdi. Mushuklar haqiqatan ham boshqa sayyoralik ekanlar.",
    userId: 1,
    author: "Komil Karimov",
    date: "2024-01-15",
    likes: 42,
    category: "hayot",
  },
  {
    id: 2,
    title: "Oshxonada ajoyib kashfiyot",
    body: "Bugun oshxonada yangi retsept sinab ko'rdim. Aslida palov pishirmoqchi edim, lekin oxirida g'alati bir taom chiqdi. Oilam buni 'kosmik palov' deb atashdi. Yaxshiyamki, mazasi yomon emas edi!",
    userId: 2,
    author: "Malika Toshmatova",
    date: "2024-01-14",
    likes: 28,
    category: "ovqat",
  },
  {
    id: 3,
    title: "Ovqat pishirishdagi dramatik portlash",
    body: "Zoom qo‘ng‘irog‘i paytida kameram tasodifan yoqilib qoldi – hammayoq chalkashdi.",
    userId: 3,
    author: "Dilshod Xudoyberdiyev",
    date: "2024-01-17",
    likes: 103,
    category: "hayot",
  },
  {
    id: 4,
    title: "Oyoq kiyim bilan moshina haydash",
    body: "Mikroto‘lqinli pechda non isitmoqchi edim, lekin ichidan portlash tovushi chiqdi...",
    userId: 4,
    author: "Komil Karimov",
    date: "2024-01-14",
    likes: 108,
    category: "kulgu",
  },
  {
    id: 5,
    title: "Kichik ukam va ketchup inqilobi",
    body: "Qorovul meni kechasi xatolik bilan o‘g‘ri deb o‘ylab, to‘xtatib qoldi!",
    userId: 3,
    author: "Gulnoza Qodirova",
    date: "2024-01-15",
    likes: 111,
    category: "ovqat",
  },
  {
    id: 6,
    title: "Ertalabki kofe bilan urush",
    body: "Bugun ertalab kofeni to'kib yubordim – bu mening to'liq uyg'onishimga sabab bo'ldi.",
    userId: 5,
    author: "Komil Karimov",
    date: "2024-01-16",
    likes: 44,
    category: "hayot",
  },
  {
    id: 7,
    title: "Uyquda gapirish fosh etildi",
    body: "Uyquda gapirayotganimni xonadoshim videoga olib ijtimoiy tarmoqqa joylashtirdi.",
    userId: 1,
    author: "Malika Toshmatova",
    date: "2024-01-17",
    likes: 70,
    category: "oilaviy",
  },
  {
    id: 8,
    title: "Selfi uchun yiqilib tushgan kun",
    body: "Selfi olishga uringan paytimda sirg‘alib yiqildim – odamlar qarab qoldi.",
    userId: 4,
    author: "Dilshod Xudoyberdiyev",
    date: "2024-01-14",
    likes: 65,
    category: "kulgu",
  },
  {
    id: 9,
    title: "Qo‘shnining mushugi va mening balkoni",
    body: "Qo‘shnining mushugi mening balkonimni o‘ziniki deb biladi.",
    userId: 2,
    author: "Komil Karimov",
    date: "2024-01-15",
    likes: 87,
    category: "hayot",
  },
  {
    id: 10,
    title: "Yangi soch turmagi – tajriba va oqibat",
    body: "Sochini yangi uslubda qirdirdim – lekin oyna oldida yig‘lagim keldi.",
    userId: 5,
    author: "Gulnoza Qodirova",
    date: "2024-01-16",
    likes: 33,
    category: "hayot",
  },
  {
    id: 11,
    title: "Tish shifokori bilan uchrashuv",
    body: "Tish shifokori hazilkash ekan – ammo men haddan ortiq jiddiy edim.",
    userId: 2,
    author: "Malika Toshmatova",
    date: "2024-01-17",
    likes: 91,
    category: "oilaviy",
  },
  {
    id: 12,
    title: "Mushuk va printer o‘rtasidagi jang",
    body: "Mening mushugim printer bilan jang qilib, uni yengib chiqdi.",
    userId: 1,
    author: "Dilshod Xudoyberdiyev",
    date: "2024-01-14",
    likes: 74,
    category: "hayot",
  },
  {
    id: 13,
    title: "Kiyim almashtirishdagi chalkashlik",
    body: "Kiyim almashtirayotgan paytimda ikkita futbolkani ustma-ust kiyib olganimni sezmadim.",
    userId: 3,
    author: "Gulnoza Qodirova",
    date: "2024-01-15",
    likes: 36,
    category: "kulgu",
  },
  {
    id: 14,
    title: "Zoom halokati",
    body: "Zoom qo‘ng‘irog‘i paytida kameram tasodifan yoqilib qoldi – hammayoq chalkashdi.",
    userId: 4,
    author: "Malika Toshmatova",
    date: "2024-01-16",
    likes: 52,
    category: "ish",
  },
  {
    id: 15,
    title: "Yangi robot changyutgich – dushman",
    body: "Yangi robot changyutgich mening oyog‘imga urildi va yugurib ketdi.",
    userId: 5,
    author: "Komil Karimov",
    date: "2024-01-17",
    likes: 100,
    category: "hayot",
  },
  {
    id: 16,
    title: "Sog‘lom ovqatlanish urinishlari",
    body: "Sog‘lom ovqatlanmoqchi bo‘ldim, lekin pizza yeb qo‘ydim.",
    userId: 2,
    author: "Gulnoza Qodirova",
    date: "2024-01-14",
    likes: 29,
    category: "ovqat",
  },
  {
    id: 17,
    title: "Bolalar bilan savdo markazida",
    body: "Bolalarni nazorat qilaman deb, savdo markazida o‘zim yo‘qoldim.",
    userId: 1,
    author: "Komil Karimov",
    date: "2024-01-15",
    likes: 77,
    category: "oilaviy",
  },
  {
    id: 18,
    title: "Mikroto‘lqinli pechning sarguzashti",
    body: "Mikroto‘lqinli pechda non isitmoqchi edim, lekin ichidan portlash tovushi chiqdi...",
    userId: 3,
    author: "Dilshod Xudoyberdiyev",
    date: "2024-01-16",
    likes: 64,
    category: "ovqat",
  },
  {
    id: 19,
    title: "Qorovul bilan to‘satdan uchrashuv",
    body: "Qorovul meni kechasi xatolik bilan o‘g‘ri deb o‘ylab, to‘xtatib qoldi!",
    userId: 2,
    author: "Malika Toshmatova",
    date: "2024-01-17",
    likes: 105,
    category: "kulgu",
  },
  {
    id: 20,
    title: "Selfi uchun yiqilib tushgan kun",
    body: "Selfi olishga uringan paytimda sirg‘alib yiqildim – odamlar qarab qoldi.",
    userId: 4,
    author: "Dilshod Xudoyberdiyev",
    date: "2024-01-14",
    likes: 65,
    category: "kulgu",
  },
];

const dramaPosts = [
  {
    id: 1,
    title: "Vaqt o'tishi haqida o'ylar",
    body: "Kecha eski fotosuratlarni ko'rib o'tirdim. Qanday tez o'tib ketgan yillar... Har bir surat - bu bir lahza, bir xotira. Ba'zan o'tmishga qaytishni xohlayman, lekin bilaman ki, oldinda yangi sarguzashtlar kutmoqda.",
    userId: 1,
    author: "Sardor Rahimov",
    date: "2024-01-15",
    likes: 156,
    category: "falsafa",
  },
  {
    id: 2,
    title: "Ona tilimizning go'zalligi",
    body: "O'zbek tili - bu bizning qalbimizning tili. Har bir so'z, har bir ibora ichida asrlar davomida to'plangan donolik mujassam. Biz bu tilni avloddan avlodga o'tkazib, uning go'zalligini saqlashimiz kerak.",
    userId: 2,
    author: "Nilufar Karimova",
    date: "2024-01-14",
    likes: 203,
    category: "madaniyat",
  },
  {
    id: 3,
    title: "Taqdir bilan yarashuv",
    body: "Hayotda har bir inson o'z taqdiriga duch keladi. Qiyinchiliklar bilan yarashish, ularni qabul qilish ham jasoratdir.",
    userId: 3,
    author: "Javohir Ismoilov",
    date: "2024-01-13",
    likes: 142,
    category: "hayot",
  },
  {
    id: 4,
    title: "Yolg‘izlikning shirin dardi",
    body: "Ba'zida yolg‘izlikni his qilish nafaqat g‘am, balki ichki tinchlik ham bo‘lishi mumkin. O‘sha sukunatda o‘zimizni topamiz.",
    userId: 4,
    author: "Dilshod Matniyozov",
    date: "2024-01-12",
    likes: 98,
    category: "falsafa",
  },
  {
    id: 5,
    title: "Kitoblar dunyosi",
    body: "Har bir kitob — bu yangi bir olam. Ularning sahifalari orasida o‘zimni yo‘qotishni yaxshi ko‘raman.",
    userId: 5,
    author: "Lola Qosimova",
    date: "2024-01-11",
    likes: 184,
    category: "adabiyot",
  },
  {
    id: 6,
    title: "Bolaligimga safar",
    body: "Uyingiz oldidagi eski daraxt hali ham o‘sha joyda turibdi. Har safar ko‘zim tushsa, bolaligim ko‘z oldimga keladi.",
    userId: 1,
    author: "Sardor Rahimov",
    date: "2024-01-10",
    likes: 173,
    category: "nostalgiya",
  },
  {
    id: 7,
    title: "Ko‘ngil aralashgan sokin tunlar",
    body: "Ba’zan kechasi tinch tursa-da, yurakda to‘lqinlar uyg‘onadi. O‘sha to‘lqinlar orqasida bir haqiqat yashiringan bo‘ladi.",
    userId: 2,
    author: "Nilufar Karimova",
    date: "2024-01-09",
    likes: 111,
    category: "ruhiyat",
  },
  {
    id: 8,
    title: "Do‘stlik haqida fikrlar",
    body: "Haqiqiy do‘stlar hayotimizdagi eng katta boyliklardan biridir. Ular bilan o‘tilgan vaqt hech qachon bekor ketmaydi.",
    userId: 3,
    author: "Javohir Ismoilov",
    date: "2024-01-08",
    likes: 220,
    category: "jamiyat",
  },
  {
    id: 9,
    title: "O‘tmishga nisbatan minnatdorchilik",
    body: "O‘tmishdagi har bir og‘riq meni shu kungacha olib keldi. Bugun minnatdorman, aynan shunday bo‘lgani uchun.",
    userId: 4,
    author: "Dilshod Matniyozov",
    date: "2024-01-07",
    likes: 90,
    category: "falsafa",
  },
  {
    id: 10,
    title: "Tushlar va haqiqatlar orasida",
    body: "Tushlar gohida haqiqatga aylanishi mumkin. Faqat ularga yetarlicha ishonsak, ularni amalga oshirish mumkin.",
    userId: 5,
    author: "Lola Qosimova",
    date: "2024-01-06",
    likes: 135,
    category: "motivatsiya",
  },
  {
    id: 11,
    title: "San’at va hayot",
    body: "San’at bu hayotning aksidir. U orqali his-tuyg‘ularimizni ifoda etamiz, yuragimizdagi og‘riqlarni bo‘lishamiz.",
    userId: 1,
    author: "Sardor Rahimov",
    date: "2024-01-05",
    likes: 188,
    category: "madaniyat",
  },
  {
    id: 12,
    title: "Ko‘z yoshlari sababi",
    body: "Yig‘laganingda har doim g‘am emas, ba’zida quvonch, ba’zida esa yengillik bo‘ladi. Har bir tomchi – bir hikoya.",
    userId: 2,
    author: "Nilufar Karimova",
    date: "2024-01-04",
    likes: 129,
    category: "ruhiyat",
  },
  {
    id: 13,
    title: "Yurak bilan o‘qish san’ati",
    body: "Kitobni ko‘z bilan emas, yurak bilan o‘qish kerak. Ana shunda u sizga so‘z bermaydigan haqiqatlarni aytadi.",
    userId: 3,
    author: "Javohir Ismoilov",
    date: "2024-01-03",
    likes: 160,
    category: "adabiyot",
  },
  {
    id: 14,
    title: "Tun va xotiralar",
    body: "Tun — bu faqat qorong‘ilik emas. U xotiralarga to‘la. Har tun — o‘tmish bilan suhbat, o‘zimiz bilan muloqotdir.",
    userId: 4,
    author: "Dilshod Matniyozov",
    date: "2024-01-02",
    likes: 95,
    category: "nostalgiya",
  },
  {
    id: 15,
    title: "Yangi yil, yangi umidlar",
    body: "Yangi yil faqat sana emas, balki yangi orzular, yangi maqsadlar uchun imkoniyatdir. O‘zgarishga qadam qo‘ying.",
    userId: 5,
    author: "Lola Qosimova",
    date: "2024-01-01",
    likes: 210,
    category: "motivatsiya",
  },
  {
    id: 16,
    title: "O‘zligingni topish yo‘li",
    body: "Inson eng avvalo o‘zini tanishi kerak. O‘zligingni anglash – hayotdagi eng muhim safarlardan biridir.",
    userId: 1,
    author: "Sardor Rahimov",
    date: "2023-12-31",
    likes: 177,
    category: "falsafa",
  },
  {
    id: 17,
    title: "Kechirim — kuch belgisi",
    body: "Kechirish zaiflik emas, kuch belgisi. Ko‘nglingni og‘ritganlarga kechirimli bo‘lish — bu o‘zini yengishdir.",
    userId: 2,
    author: "Nilufar Karimova",
    date: "2023-12-30",
    likes: 186,
    category: "ruhiyat",
  },
  {
    id: 18,
    title: "Ko'z yoshlari ortidagi quvonch",
    body: "Ba'zan inson kulgining orqasida ham og'riq yashirinadi. Ammo har bir ko'z yoshi bizni kuchliroq qiladi. Har bir sinov, oxir-oqibat, bizni baxtga eltuvchi yo'l bo'lishi mumkin.",
    userId: 4,
    author: "Murod Qodirov",
    date: "2024-01-30",
    likes: 121,
    category: "hayotiy",
  },
  {
    id: 19,
    title: "Yolg‘izlikning ovozi",
    body: "Tun yarmida uyg'onib, jimjitlikni tinglash... Yolg'izlik ba'zida og'riqli, ba'zida esa ruhiy tinchlik olib keladi. Bu holatni qabul qilgan kishi o'zini chinakam tushuna boshlaydi.",
    userId: 5,
    author: "Shahzoda Ergasheva",
    date: "2024-01-31",
    likes: 89,
    category: "psixologiya",
  },
  {
    id: 20,
    title: "Umid so‘nmas yulduzdir",
    body: "Qanchalik zulmat bo'lmasin, yurakda umid bo'lsa, har doim bir nur yo'l ko‘rsatadi. Har bir inson umid bilan yashaydi, chunki u bizni ertaga olib boradi.",
    userId: 6,
    author: "Jamshid Shukurov",
    date: "2024-02-01",
    likes: 142,
    category: "motivatsiya",
  },
];

const romancePosts = [
  {
    id: 1,
    title: "Bahor sevgisi",
    body: "Bahor keldi, va men yana sevib qoldim. Bu safar olmalar gullagan bog'da, quyosh nuri ostida. Uning kulgi ovozi shamol bilan aralashib, qalbimda abadiy saqlanib qoldi. Sevgi - bu eng go'zal his.",
    userId: 1,
    author: "Jasur Alimov",
    date: "2024-01-15",
    likes: 89,
    category: "sevgi",
  },
  {
    id: 2,
    title: "Birinchi uchrashuv",
    body: "Kitob do'konida uchrashgan edik. U she'riyat bo'limida turgan edi, men esa roman qidirayotgan edim. Bir kitob uchun ikkalamiz qo'l uzatganimizda, qo'llarimiz tegishdi. O'sha lahzada vaqt to'xtab qolgandek bo'ldi.",
    userId: 2,
    author: "Gulnora Yusupova",
    date: "2024-01-14",
    likes: 134,
    category: "sevgi",
  },
  {
    id: 3,
    title: "Yomg‘irdagi tanishuv",
    body: "Yomg'ir ostida holsiz yurgan paytimda u menga soyabon tutdi. Shu kichkina e’tibor yuragimni zabt etdi. Har yomg‘ir yog‘ganda uni eslayman.",
    userId: 3,
    author: "Zafar Mo‘minov",
    date: "2024-02-10",
    likes: 72,
    category: "sevgi",
  },
  {
    id: 4,
    title: "Qog‘ozdagi yurak",
    body: "Maktabda unga birinchi marta qog‘oz yurak yasab bergandim. Oradan yillar o'tdi, u o'sha yurakni hanuz saqlab yurarkan.",
    userId: 4,
    author: "Nigora Kamilova",
    date: "2024-02-13",
    likes: 98,
    category: "sevgi",
  },
  {
    id: 5,
    title: "Qor ostidagi sevgi",
    body: "Qorli tongda bir-birimizni ilk bor ko‘rdik. Oppoq dunyo ichida qalbimiz iliq tuyg‘ular bilan to‘ldi.",
    userId: 5,
    author: "Sherzod Abdurahmonov",
    date: "2024-02-15",
    likes: 111,
    category: "sevgi",
  },
  {
    id: 6,
    title: "Tunlar sadosi",
    body: "U bilan har kecha telefon orqali gaplashib, tongga qadar orzular qurardik. U tunlar menga yorug‘likdek edi.",
    userId: 1,
    author: "Jasur Alimov",
    date: "2024-03-01",
    likes: 123,
    category: "sevgi",
  },
  {
    id: 7,
    title: "Kinoda boshlangan sevgi",
    body: "Kinoteatrda yonimdagi joyga o'tiribdi. Film tugagach, ikkovimiz ham ko‘z yosh to‘kkan edik. Shu kundan boshlab har bir filmimiz o‘zimizniki bo‘ldi.",
    userId: 6,
    author: "Dilnoza Qudratova",
    date: "2024-03-05",
    likes: 77,
    category: "sevgi",
  },
  {
    id: 8,
    title: "Xatdagi izhor",
    body: "Unga sevgi maktubi yozdim. U xatni bir necha kun o‘qimadi, lekin keyin javobi yuragimni larzaga soldi.",
    userId: 7,
    author: "Tohir Jabborov",
    date: "2024-03-08",
    likes: 69,
    category: "sevgi",
  },
  {
    id: 9,
    title: "Musaffo osmon ostida",
    body: "U bilan yulduzli osmon ostida yotib, orzularimizni gaplashardik. Har yulduz bizning bitta orzumiz edi.",
    userId: 2,
    author: "Gulnora Yusupova",
    date: "2024-03-10",
    likes: 88,
    category: "sevgi",
  },
  {
    id: 10,
    title: "Kutilmagan sovg‘a",
    body: "Men tug‘ilgan kunimda hech nima kutmagan edim. Lekin u kelib, o‘zini sovg‘a qildi – bu eng katta baxtim bo‘ldi.",
    userId: 8,
    author: "Shahzoda Karimova",
    date: "2024-03-14",
    likes: 115,
    category: "sevgi",
  },
  {
    id: 11,
    title: "Sevgi avtobusda boshlanadi",
    body: "Har kuni bir xil avtobusga chiqdim, faqat uni ko‘rish uchun. Bir kun u yonimga o'tirib, kulib dedi: 'Bugun men seni kutdim.'",
    userId: 9,
    author: "Jamshid Xolmatov",
    date: "2024-03-20",
    likes: 94,
    category: "sevgi",
  },
  {
    id: 12,
    title: "Bahorda olingan surat",
    body: "U bilan birga tushgan suratimni har bahor qo‘limga olib qarayman. Rangi xiralashgan, ammo hislar hanuz jonli.",
    userId: 10,
    author: "Lola Sa’dullayeva",
    date: "2024-03-25",
    likes: 101,
    category: "sevgi",
  },
  {
    id: 13,
    title: "Kitobdagi sevgi",
    body: "U menga bir sevgi romani sovg‘a qildi. Sahifalar orasida yuragimni topdim. Har o‘qiganimda uni eslayman.",
    userId: 11,
    author: "Qobil Berdiev",
    date: "2024-03-28",
    likes: 56,
    category: "sevgi",
  },
  {
    id: 14,
    title: "Ko‘ngil ko‘zlari",
    body: "U ko‘zlarimga qaradi. So‘zsiz gaplashdik. Sevgi ko‘rinmaydi, lekin yurak uni darhol taniydi.",
    userId: 12,
    author: "Malika Nuriddinova",
    date: "2024-04-01",
    likes: 78,
    category: "sevgi",
  },
  {
    id: 15,
    title: "Bir piyola choy",
    body: "Sovuq kunda birga ichilgan choy, qalbimizdagi iliqlikni boshqacha his qildirdi. Choy emas, muhabbat edi bizni isitgan.",
    userId: 13,
    author: "Alisher Oripov",
    date: "2024-04-04",
    likes: 82,
    category: "sevgi",
  },
  {
    id: 16,
    title: "Daryo bo‘yida",
    body: "Daryo bo‘yida birga yurib, jim-jitlikda bir-birimizni angladik. Har so‘zimizni suv oqizi olib ketgandek, lekin yurakda qoldi.",
    userId: 14,
    author: "Rayhona Sobirova",
    date: "2024-04-06",
    likes: 67,
    category: "sevgi",
  },
  {
    id: 17,
    title: "So‘nggi qo‘ng‘iroq",
    body: "Maktab tugayotganda, u menga bir gul berdi. Endi esa har gal lola ko‘rsam, uni eslayman.",
    userId: 15,
    author: "Javohir To‘xtayev",
    date: "2024-04-10",
    likes: 103,
    category: "sevgi",
  },
  {
    id: 18,
    title: "Parvozdagi orzular",
    body: "Samolyotda yonimga tushib qoldi. Parvoz davomida gaplashdik, tushganimizda esa telefon raqamlar almashdik. Endi har parvozda yuragim unga uchadi.",
    userId: 16,
    author: "Sevara Asatullayeva",
    date: "2024-04-14",
    likes: 93,
    category: "sevgi",
  },
  {
    id: 19,
    title: "Tunlar va xatlar",
    body: "Uzoq masofadan yozilgan har bir maktubi yuragimni ezardi. Ammo har harfi sevgiga to‘la edi.",
    userId: 17,
    author: "Murod Ismoilov",
    date: "2024-04-18",
    likes: 99,
    category: "sevgi",
  },
  {
    id: 20,
    title: "Qayta uchrashuv",
    body: "Oradan besh yil o'tib ko‘chada tasodifan yana ko‘rishdik. Uning nigohi hali ham qalbimni larzaga soladi.",
    userId: 18,
    author: "Madina Ergasheva",
    date: "2024-04-22",
    likes: 141,
    category: "sevgi",
  },
];

const adventurePosts = [
  {
    id: 1,
    title: "Chimyon tog'laridagi sarguzasht",
    body: "Chimyon tog'lariga ko'tarilish - bu haqiqiy sinov edi. Qiyalik yo'llar, noma'lum burilishlar, va eng muhimi - cho'qqida kutayotgan ajoyib manzara. Tog'lar bizga sabr va qat'iyatni o'rgatadi.",
    userId: 1,
    author: "Bobur Nazarov",
    date: "2024-01-15",
    likes: 67,
    category: "sayohat",
  },
  {
    id: 2,
    title: "Samarqand yo'llarida",
    body: "Samarqandga sayohat - bu vaqt mashinasida sayohat qilishga o'xshaydi. Registon maydonida turganda, o'zingni Amir Temur davrida his qilasan. Har bir tosh, har bir naqsh tarix haqida gapiradi.",
    userId: 2,
    author: "Zarina Mirzayeva",
    date: "2024-01-14",
    likes: 198,
    category: "sayohat",
  },
  {
    id: 3,
    title: "Qoraqalpog‘istonning cho‘llari",
    body: "Cho‘lni kechish — bu jimjitlik va tabiat bilan yolg‘iz qolish. Quvurlar tagidagi suvlar, kaktuslar va quyosh botishi — hammasi bir sarguzashtning bo‘lagi.",
    userId: 3,
    author: "Shahzod Qodirov",
    date: "2024-01-13",
    likes: 53,
    category: "sayohat",
  },
  {
    id: 4,
    title: "Xorazm — qadimiy hikoyalar yurti",
    body: "Ichan qal’aga kirgan zahotingiz tarix sizni qamrab oladi. Har bir ko‘cha, har bir minorasi sizga o‘tmishdan so‘zlaydi.",
    userId: 4,
    author: "Dilshod Karimov",
    date: "2024-01-13",
    likes: 72,
    category: "sayohat",
  },
  {
    id: 5,
    title: "Orol dengizi izidan",
    body: "Orol dengizi o‘rnida qolgan qum va qayiq skeletlari qalbingizni larzaga soladi. Bu yerda yo‘qotilgan hayotlar izlari bor.",
    userId: 5,
    author: "Madina Xusanova",
    date: "2024-01-12",
    likes: 101,
    category: "sayohat",
  },
  {
    id: 6,
    title: "Boysun daralaridagi tunda",
    body: "Tun Boysun tog‘larida — yulduzlar ostida o't o‘chirish, olov atrofida hikoyalar aytish va yurakdan kulish demakdir.",
    userId: 6,
    author: "Javlonbek Sattorov",
    date: "2024-01-11",
    likes: 45,
    category: "sayohat",
  },
  {
    id: 7,
    title: "Zomin oromgohi — tinchlik manzili",
    body: "Zominning yashil o‘rmonlarida yurish, soyning shovqini ostida dam olish — bu ruhiy tiklanishning manbai.",
    userId: 7,
    author: "Gulchehra Raxmatova",
    date: "2024-01-10",
    likes: 66,
    category: "sayohat",
  },
  {
    id: 8,
    title: "Beldersoyda chang'i uchish",
    body: "Beldersoydagi qorli tog‘lar, chang‘i sporti va issiq choy — bu qishki sarguzashtning eng yaxshi ifodasi.",
    userId: 8,
    author: "Iskandar Komilov",
    date: "2024-01-09",
    likes: 84,
    category: "sayohat",
  },
  {
    id: 9,
    title: "Qo'qon — hunarmandlar shahri",
    body: "Qo‘qonning bozorlarida yurish, zardo‘zlik va kulolchilik san’atini tomosha qilish o‘ziga xos tajriba bo‘ladi.",
    userId: 9,
    author: "Shoira Toirova",
    date: "2024-01-08",
    likes: 95,
    category: "sayohat",
  },
  {
    id: 10,
    title: "Hisor darasidan o'tish",
    body: "Hisor darasi — bu sarguzashtni sevuvchilar uchun sinov. Keskin burilishlar, muzli daryo va toshli yo‘llar.",
    userId: 10,
    author: "Jamshid Mahmudov",
    date: "2024-01-07",
    likes: 38,
    category: "sayohat",
  },
  {
    id: 11,
    title: "Nurota tog'larida trekking",
    body: "Nurota tog‘lari tinch va go‘zal. Tog‘ etaklarida yurish, tabiat bilan uyg‘unlikda bo‘lish — bu hayotni qadrlashdir.",
    userId: 11,
    author: "Nilufar G‘ofurova",
    date: "2024-01-06",
    likes: 61,
    category: "sayohat",
  },
  {
    id: 12,
    title: "Toshkent metro sarguzashti",
    body: "Har bir bekat — san’at asari. Toshkent metrosi orqali yurish bu nafaqat transport, balki madaniyat safari hamdir.",
    userId: 12,
    author: "Tohir Akbarov",
    date: "2024-01-06",
    likes: 119,
    category: "sayohat",
  },
  {
    id: 13,
    title: "Asaka avtomobil zavodi safari",
    body: "Zavod ichidagi avtomat tizimlar, ishlab chiqarish bosqichlari — bu texnik sarguzashtni sevuvchilar uchun jannat.",
    userId: 13,
    author: "Olim Mirzayev",
    date: "2024-01-05",
    likes: 87,
    category: "sayohat",
  },
  {
    id: 14,
    title: "Mo‘ynoqdagi qum festival",
    body: "Sahrodagi musiqa, raqs va odamlar — bu qum ustida kechayotgan hayot bayrami. Har qadam yangi taassurot.",
    userId: 14,
    author: "Saodatxon Nuriddinova",
    date: "2024-01-04",
    likes: 73,
    category: "sayohat",
  },
  {
    id: 15,
    title: "Chorvoq suv ombori bo‘yida",
    body: "Chorvoq — bu issiq kunlarda salqinlik, do‘stlar bilan kemada sayr qilish va suvga sho‘ng‘ish zavqi.",
    userId: 15,
    author: "Azizbek Rajabov",
    date: "2024-01-03",
    likes: 99,
    category: "sayohat",
  },
  {
    id: 16,
    title: "Farg‘ona vodiysidagi tong",
    body: "Tongda vodiyda yurish — quyosh chiqqan paytdagi tabiat uyg‘onishini ko‘rish, bu unutilmas lahza.",
    userId: 16,
    author: "Sayyora Abdullayeva",
    date: "2024-01-02",
    likes: 102,
    category: "sayohat",
  },
  {
    id: 17,
    title: "Qamchiq dovoni bo‘ylab sayohat",
    body: "Qamchiqdan o‘tish — bu balandlik, burilish va tog‘ havosi bilan to‘yingan sarguzashtdir.",
    userId: 17,
    author: "Bekzod Mamatqulov",
    date: "2024-01-01",
    likes: 55,
    category: "sayohat",
  },
  {
    id: 18,
    title: "Surxondaryo chegara hududlari",
    body: "Chegara hududlarida yurish — notanish odamlar, yangi urf-odatlar va kutilmagan mehmondo‘stlik.",
    userId: 18,
    author: "Dilafruz Yuldasheva",
    date: "2023-12-31",
    likes: 44,
    category: "sayohat",
  },
  {
    id: 19,
    title: "Andijon suv ombori bo‘yida",
    body: "Suv ustidagi tonggi sukunat, baliqchilar bilan suhbat — bu sokinlikni qadrlovchilar uchun mo‘jiza.",
    userId: 19,
    author: "Erkin Jo‘rayev",
    date: "2023-12-30",
    likes: 59,
    category: "sayohat",
  },
  {
    id: 20,
    title: "Tyan-Shan etaklarida",
    body: "Tyan-Shan tog‘ etaklari — bu baland tog‘lar va past vodiylar uyg‘unligi. Har bir qadamda hayrat va ilhom.",
    userId: 20,
    author: "Gulbahor Xoliqova",
    date: "2023-12-29",
    likes: 77,
    category: "sayohat",
  },
];

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const style = searchParams.get("style") || "comedy";
  const limit = Number.parseInt(searchParams.get("_limit") || "10");
  const page = Number.parseInt(searchParams.get("_page") || "1");

  let posts;
  switch (style) {
    case "drama":
      posts = dramaPosts;
      break;
    case "romance":
      posts = romancePosts;
      break;
    case "adventure":
      posts = adventurePosts;
      break;
    default:
      posts = comedyPosts;
  }

  // Simulate pagination
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const paginatedPosts = posts.slice(startIndex, endIndex);

  return NextResponse.json(paginatedPosts);
}
