import { type NextRequest, NextResponse } from "next/server";

const comedyUsers = [
  {
    id: 1,
    name: "Komil Karimov",
    username: "komil_kulgi",
    email: "komil@uzbekjson.uz",
    phone: "+998-90-123-45-67",
    website: "komil-kulgi.uz",
    bio: "Hayotni kulgili tomoni bilan ko'raman 😄",
    city: "Toshkent",
    profession: "Komediyachi",
    hobbies: ["hazil qilish", "kitob o'qish", "futbol"],
  },
  {
    id: 2,
    name: "Malika Toshmatova",
    username: "malika_chef",
    email: "malika@uzbekjson.uz",
    phone: "+998-91-234-56-78",
    website: "malika-oshpaz.uz",
    bio: "Oshxonada sehrgar, hayotda optimist ✨",
    city: "Samarqand",
    profession: "Oshpaz",
    hobbies: ["ovqat pishirish", "rasm chizish", "bog'bonchilik"],
  },
  {
    id: 3,
    name: "Zafar Qodirov",
    username: "zafar_smile",
    email: "zafar@uzbekjson.uz",
    phone: "+998-93-333-22-11",
    website: "zafar-qiziqarli.uz",
    bio: "Kulgu orqali hayotni o'zgartiramiz",
    city: "Buxoro",
    profession: "Aktyor",
    hobbies: ["kino ko‘rish", "parodiyalar", "yurish"],
  },
  {
    id: 4,
    name: "Dilshod Egamberdiyev",
    username: "dilshod_kulgi",
    email: "dilshod@uzbekjson.uz",
    phone: "+998-94-444-44-44",
    website: "dilshod-standup.uz",
    bio: "Stand-up mening hayotim",
    city: "Namangan",
    profession: "Stand-up komik",
    hobbies: ["stand-up yozish", "mushohada", "intervyular ko‘rish"],
  },
  {
    id: 5,
    name: "Rano Yoqubova",
    username: "rano_lol",
    email: "rano@uzbekjson.uz",
    phone: "+998-95-555-55-55",
    website: "rano-kulgu.uz",
    bio: "Har kunimda bir tabassum",
    city: "Andijon",
    profession: "Bloger",
    hobbies: ["video montaj", "kontent yaratish", "meme qilish"],
  },
  {
    id: 6,
    name: "Shuhrat Sodiqov",
    username: "shuhrat_meme",
    email: "shuhrat@uzbekjson.uz",
    phone: "+998-97-111-22-33",
    website: "shuhrat-meme.uz",
    bio: "Memelar orqali kuldiraman",
    city: "Farg‘ona",
    profession: "Meme-maker",
    hobbies: ["memelar yaratish", "kino parodiya", "komediya yozish"],
  },
  {
    id: 7,
    name: "Sadoqat G‘ulomova",
    username: "sadoqat_qiziq",
    email: "sadoqat@uzbekjson.uz",
    phone: "+998-93-765-43-21",
    website: "sadoqat-kulgi.uz",
    bio: "Kulgili hikoyalar yozaman",
    city: "Navoiy",
    profession: "Yozuvchi",
    hobbies: ["hikoya yozish", "tasvirlash", "audiokitob tinglash"],
  },
  {
    id: 8,
    name: "Botir Inoyatov",
    username: "botir_kulgu",
    email: "botir@uzbekjson.uz",
    phone: "+998-98-876-54-32",
    website: "botir-hazil.uz",
    bio: "Yaxshi hazil yaxshi kun boshlanishidir",
    city: "Xorazm",
    profession: "Tiktoker",
    hobbies: ["video olish", "reaktsiya qilish", "sketchlar qilish"],
  },
  {
    id: 9,
    name: "Dilnoza Xolmatova",
    username: "dilnoza_fun",
    email: "dilnoza@uzbekjson.uz",
    phone: "+998-91-909-80-70",
    website: "dilnoza-kulgu.uz",
    bio: "Qiziqarli kontent — mening ishim",
    city: "Qarshi",
    profession: "Kontent yaratuvchi",
    hobbies: ["video tahrirlash", "hazil postlar", "memes"],
  },
  {
    id: 10,
    name: "Javohir Matyoqubov",
    username: "javohir_smile",
    email: "javohir@uzbekjson.uz",
    phone: "+998-99-101-20-30",
    website: "javohir-kulgu.uz",
    bio: "Hayotni yengil qabul qilaylik",
    city: "Termiz",
    profession: "Kulguchi",
    hobbies: ["kitob o‘qish", "podkastlar", "piyoda sayr"],
  },
  {
    id: 11,
    name: "Shahzoda Murotova",
    username: "shahzoda_kulgi",
    email: "shahzoda@uzbekjson.uz",
    phone: "+998-90-876-12-34",
    website: "shahzoda-fun.uz",
    bio: "Odamlarni quvontirish — katta savob",
    city: "Jizzax",
    profession: "YouTube blogger",
    hobbies: ["blog yozish", "musiqa tinglash", "sayohat"],
  },
  {
    id: 12,
    name: "Azamat Beknazarov",
    username: "azamat_qiziqchi",
    email: "azamat@uzbekjson.uz",
    phone: "+998-92-654-32-10",
    website: "azamat-lol.uz",
    bio: "Kulgini jiddiylikdan ustun qo‘yamiz",
    city: "Guliston",
    profession: "Aktyor",
    hobbies: ["filmda suratga tushish", "hazillar yaratish", "o‘qish"],
  },
  {
    id: 13,
    name: "Muhammad Sattorov",
    username: "muhammad_joyful",
    email: "muhammad@uzbekjson.uz",
    phone: "+998-93-345-67-89",
    website: "muhammad-smile.uz",
    bio: "Tabassum bilan yashang",
    city: "Toshkent",
    profession: "Radio boshlovchisi",
    hobbies: ["efirda gapirish", "audiolar yozish", "ko‘ngilochar dasturlar"],
  },
  {
    id: 14,
    name: "Ozoda Qodirova",
    username: "ozoda_kulgu",
    email: "ozoda@uzbekjson.uz",
    phone: "+998-97-123-45-67",
    website: "ozoda-funny.uz",
    bio: "Qiziqarli suhbatlar – mening kuchim",
    city: "Qo‘qon",
    profession: "MC",
    hobbies: ["sahna", "gapirish", "kuldirish"],
  },
  {
    id: 15,
    name: "Sherzod Abdullayev",
    username: "sherzod_qiziq",
    email: "sherzod@uzbekjson.uz",
    phone: "+998-94-321-67-89",
    website: "sherzod-standup.uz",
    bio: "Kuldirish – bu san’at",
    city: "Andijon",
    profession: "Stand-up artist",
    hobbies: ["monolog yozish", "video olish", "xalq bilan ishlash"],
  },
  {
    id: 16,
    name: "Gulchehra Norboyeva",
    username: "gulchehra_funny",
    email: "gulchehra@uzbekjson.uz",
    phone: "+998-91-777-88-99",
    website: "gulchehra-smile.uz",
    bio: "Kulgu bilan hayot rang-barang",
    city: "Marg‘ilon",
    profession: "Kulgu bloger",
    hobbies: ["tik tok video", "oila bilan vaqt o‘tkazish", "hazil tinglash"],
  },
  {
    id: 17,
    name: "Abduqodir Islomov",
    username: "abduqodir_hazil",
    email: "abduqodir@uzbekjson.uz",
    phone: "+998-90-222-33-44",
    website: "abduqodir-fun.uz",
    bio: "Har kungi hazil – sog‘liq uchun foydali",
    city: "Shahrisabz",
    profession: "Ssenarist",
    hobbies: ["kino ssenariy", "komik yozish", "qahva ichish"],
  },
  {
    id: 18,
    name: "Shoira Mamadaliyeva",
    username: "shoira_fun",
    email: "shoira@uzbekjson.uz",
    phone: "+998-98-888-77-66",
    website: "shoira-lol.uz",
    bio: "Hazilni yurakdan sevarman",
    city: "Nukus",
    profession: "TikToker",
    hobbies: ["tik tok trendlar", "sketchlar", "musiqa montaj"],
  },
  {
    id: 19,
    name: "Jasur Teshaboyev",
    username: "jasur_comedy",
    email: "jasur@uzbekjson.uz",
    phone: "+998-91-555-66-77",
    website: "jasur-kulgi.uz",
    bio: "O‘zgacha kulgu, o‘zgacha kayfiyat",
    city: "Chirchiq",
    profession: "Rejissyor",
    hobbies: [
      "film suratga olish",
      "aktiyorlar bilan ishlash",
      "komediya tahlil qilish",
    ],
  },
  {
    id: 20,
    name: "Zarnigor Ubaydullayeva",
    username: "zarnigor_fun",
    email: "zarnigor@uzbekjson.uz",
    phone: "+998-93-333-99-88",
    website: "zarnigor-funny.uz",
    bio: "Kulgu yuragimdagi eng chiroyli tovush",
    city: "Angren",
    profession: "Yozuvchi",
    hobbies: ["kulgu hikoyalar", "blog yuritish", "sayr qilish"],
  },
];

const dramaUsers = [
  {
    id: 1,
    name: "Sardor Rahimov",
    username: "sardor_poet",
    email: "sardor@uzbekjson.uz",
    phone: "+998-93-345-67-89",
    website: "sardor-sher.uz",
    bio: "So'zlar orqali qalblarni terib beraman 💫",
    city: "Buxoro",
    profession: "Shoir",
    hobbies: ["she'r yozish", "musiqa tinglash", "tabiat bilan suhbat"],
  },
  {
    id: 2,
    name: "Nilufar Karimova",
    username: "nilufar_writer",
    email: "nilufar@uzbekjson.uz",
    phone: "+998-94-456-78-90",
    website: "nilufar-yozuvchi.uz",
    bio: "Har bir so'z - qalb zarbasidek 💝",
    city: "Farg'ona",
    profession: "Yozuvchi",
    hobbies: ["kitob yozish", "sayohat", "san'at"],
  },
  {
    id: 3,
    name: "Oybek Sodiqov",
    username: "oybek_dramaturg",
    email: "oybek@uzbekjson.uz",
    phone: "+998-95-123-00-11",
    website: "oybek-dramatik.uz",
    bio: "Sahna uchun yashayman, sahnada yig'layman 🎭",
    city: "Andijon",
    profession: "Dramaturg",
    hobbies: ["pyesa yozish", "teatrga borish", "qahva ichish"],
  },
  {
    id: 4,
    name: "Madina Raximova",
    username: "madina_aktrisa",
    email: "madina@uzbekjson.uz",
    phone: "+998-97-765-43-21",
    website: "madina-teatr.uz",
    bio: "Ko'z yoshsiz drama yo‘q 👁️‍🗨️",
    city: "Namangan",
    profession: "Aktrisa",
    hobbies: ["aktyorlik", "qog'ozga tuyg'u to‘kib yozish", "fotografiya"],
  },
  {
    id: 5,
    name: "Jahongir Xudoyberdiyev",
    username: "jahongir_roman",
    email: "jahongir@uzbekjson.uz",
    phone: "+998-93-112-22-33",
    website: "jahongir-roman.uz",
    bio: "Har bob — bir armon 📖",
    city: "Xiva",
    profession: "Romannavis",
    hobbies: ["roman yozish", "kitob o‘qish", "kechqurun yurish"],
  },
  {
    id: 6,
    name: "Dilnoza Ermatova",
    username: "dilnoza_dard",
    email: "dilnoza@uzbekjson.uz",
    phone: "+998-91-876-54-32",
    website: "dilnoza-doston.uz",
    bio: "Har satrimda bir dard yashirin 💔",
    city: "Qarshi",
    profession: "Dostonchi",
    hobbies: ["she'r aytish", "qadimgi dostonlar", "san'at"],
  },
  {
    id: 7,
    name: "Sherzod Mahmudov",
    username: "sherzod_scene",
    email: "sherzod@uzbekjson.uz",
    phone: "+998-90-345-67-89",
    website: "sherzod-teatr.uz",
    bio: "Hayot sahna bo‘lsa, men aktyorman 🎬",
    city: "Navoiy",
    profession: "Aktyor",
    hobbies: ["rol o‘rganish", "film ko‘rish", "ovoz mashqlari"],
  },
  {
    id: 8,
    name: "Gulrux Yuldasheva",
    username: "gulrux_melodrama",
    email: "gulrux@uzbekjson.uz",
    phone: "+998-99-222-33-44",
    website: "gulrux-dramatik.uz",
    bio: "Yuragimni sahifalarga to‘kaman 📜",
    city: "Toshkent",
    profession: "Stsenarist",
    hobbies: ["film yozish", "yozishmalar", "ko‘z yosh yig‘ish"],
  },
  {
    id: 9,
    name: "Rustam Xasanov",
    username: "rustam_roman",
    email: "rustam@uzbekjson.uz",
    phone: "+998-98-556-67-78",
    website: "rustam-adabiyot.uz",
    bio: "Har bir kitobim — bir iztirob 📚",
    city: "Sirdaryo",
    profession: "Yozuvchi",
    hobbies: ["monolog yozish", "qahvaxonada o‘tirish", "adabiyot"],
  },
  {
    id: 10,
    name: "Shahnoza Abdurahmonova",
    username: "shahnoza_doston",
    email: "shahnoza@uzbekjson.uz",
    phone: "+998-97-909-08-07",
    website: "shahnoza-doston.uz",
    bio: "Og‘ir so‘zlarim yurakka borib tegadi 🥀",
    city: "Jizzax",
    profession: "Dostonchi",
    hobbies: ["qo‘shiq aytish", "she’r yozish", "teatr tomosha qilish"],
  },
  {
    id: 11,
    name: "Murod Qodirov",
    username: "murod_script",
    email: "murod@uzbekjson.uz",
    phone: "+998-90-223-45-66",
    website: "murod-script.uz",
    bio: "Film uchun har bir sahna yurakdan chiqadi 💔",
    city: "Toshkent",
    profession: "Ssenariy muallifi",
    hobbies: ["kino yozish", "analiz qilish", "drama ko‘rish"],
  },
  {
    id: 12,
    name: "Ziyoda Mamatqulova",
    username: "ziyoda_dramaqueen",
    email: "ziyoda@uzbekjson.uz",
    phone: "+998-91-665-43-21",
    website: "ziyoda-qirolicha.uz",
    bio: "Hayotda doim sahna bor, siz faqat rolingizni bajaring.",
    city: "Termiz",
    profession: "Aktrisa",
    hobbies: ["sahna san’ati", "musiqa", "nutq ustida ishlash"],
  },
  {
    id: 13,
    name: "Akmal To‘raqulov",
    username: "akmal_rejisyor",
    email: "akmal@uzbekjson.uz",
    phone: "+998-90-334-22-11",
    website: "akmal-film.uz",
    bio: "Kamera ortidan yuraklarni larzaga keltiraman 🎥",
    city: "Qo‘qon",
    profession: "Rejissyor",
    hobbies: ["film suratga olish", "drama sahnalashtirish", "sokin musiqa"],
  },
  {
    id: 14,
    name: "Sitora Norqobilova",
    username: "sitora_eyes",
    email: "sitora@uzbekjson.uz",
    phone: "+998-93-123-45-67",
    website: "sitora-kozyosh.uz",
    bio: "Ko‘zlarim bilan so‘zlayman... 🥲",
    city: "Urganch",
    profession: "Aktrisa",
    hobbies: ["ko‘z yoshi mashqlari", "drama rollar", "ko‘zguga qarash"],
  },
  {
    id: 15,
    name: "Diyorbek Mamatov",
    username: "diyorbek_ruh",
    email: "diyorbek@uzbekjson.uz",
    phone: "+998-92-234-56-78",
    website: "diyorbek-ruh.uz",
    bio: "Tuyg‘ularimni so‘zga aylantiraman ✍️",
    city: "Zarafshon",
    profession: "Yozuvchi",
    hobbies: ["kechalar o‘ylash", "she’r yozish", "yolg‘izlik"],
  },
  {
    id: 16,
    name: "Shaxzoda Jo‘rayeva",
    username: "shaxzoda_dardlar",
    email: "shaxzoda@uzbekjson.uz",
    phone: "+998-91-908-70-60",
    website: "shaxzoda-qoraqalpoq.uz",
    bio: "Yuragimni qo‘lim bilan yozaman.",
    city: "Nukus",
    profession: "Shoira",
    hobbies: ["dard to‘kib yozish", "qo‘shiq matnlari", "monologlar"],
  },
  {
    id: 17,
    name: "Shuhrat Aliyev",
    username: "shuhrat_poet",
    email: "shuhrat@uzbekjson.uz",
    phone: "+998-93-333-22-11",
    website: "shuhrat-satr.uz",
    bio: "She’rda dardimni aytaman, ko‘zda emas.",
    city: "Guliston",
    profession: "Shoir",
    hobbies: ["so‘z o‘yinlari", "kechqurun yozish", "yulduzlarga qarash"],
  },
  {
    id: 18,
    name: "Muslima To‘xtayeva",
    username: "muslima_dramatic",
    email: "muslima@uzbekjson.uz",
    phone: "+998-93-545-67-89",
    website: "muslima-drama.uz",
    bio: "Hayot o‘zi bir spektakl, men faqat rol o‘ynayman.",
    city: "Angren",
    profession: "Aktrisa",
    hobbies: ["sahna mashqlari", "nutq yozish", "yig‘lash san’ati"],
  },
  {
    id: 19,
    name: "Temurbek Rajabov",
    username: "temurbek_stage",
    email: "temurbek@uzbekjson.uz",
    phone: "+998-97-606-70-60",
    website: "temurbek-stage.uz",
    bio: "Teatr — men uchun ibodatxona.",
    city: "Toshkent",
    profession: "Dramaturg",
    hobbies: ["drama tahlili", "kitob yozish", "rol bo‘yicha suhbatlar"],
  },
  {
    id: 20,
    name: "Zarnigor Akbarova",
    username: "zarnigor_qissalar",
    email: "zarnigor@uzbekjson.uz",
    phone: "+998-90-101-02-03",
    website: "zarnigor-doston.uz",
    bio: "Har doston — yuragim parchalari",
    city: "Denov",
    profession: "Shoira",
    hobbies: ["epik dostonlar", "she’rlar yig‘ish", "ko‘z yoshi bilan yozish"],
  },
];

const romanceUsers = [
  {
    id: 1,
    name: "Lola Rustamova",
    username: "lola_lirik",
    email: "lola@uzbekjson.uz",
    phone: "+998-91-123-45-67",
    website: "lolaromance.uz",
    bio: "Muhabbat yurakdan boshlanadi 💖",
    city: "Toshkent",
    profession: "Lirik yozuvchi",
    hobbies: ["she'r yozish", "mumtoz musiqa", "oyna qarshisida raqs"],
  },
  {
    id: 2,
    name: "Kamoliddin Jo‘rayev",
    username: "kamol_sher",
    email: "kamol@uzbekjson.uz",
    phone: "+998-90-234-56-78",
    website: "kamolsher.uz",
    bio: "So‘z yurakdan chiqsa, yurakka yetadi ❤️",
    city: "Samarqand",
    profession: "Shoir",
    hobbies: ["tungi sayr", "romantik kino", "sham yorug‘ida yozish"],
  },
  {
    id: 3,
    name: "Nilufar Egamberdiyeva",
    username: "nilushka_love",
    email: "nilufar@uzbekjson.uz",
    phone: "+998-91-345-67-89",
    website: "nilulove.uz",
    bio: "Muhabbatni har harfda izlayman 🌹",
    city: "Buxoro",
    profession: "Romantik hikoyachi",
    hobbies: ["san’at", "yog‘ochdan gullar yasash", "romantik romanlar"],
  },
  {
    id: 4,
    name: "Sherzod Murodov",
    username: "sherzod_qalb",
    email: "sherzod@uzbekjson.uz",
    phone: "+998-93-456-78-90",
    website: "qalbdan.uz",
    bio: "Yurakni tinglab yozaman 💌",
    city: "Namangan",
    profession: "Poet",
    hobbies: ["she’r", "dengiz manzaralari", "suratga olish"],
  },
  {
    id: 5,
    name: "Zulfiya Qodirova",
    username: "zulfiyushka",
    email: "zulfiya@uzbekjson.uz",
    phone: "+998-95-123-45-67",
    website: "zulfiyalyrics.uz",
    bio: "Muhabbatli satrlar bilan yashayman 💕",
    city: "Andijon",
    profession: "Bloger",
    hobbies: [
      "laylaklar rasmini chizish",
      "romantik audio yozuvlar",
      "shamlar yig‘ish",
    ],
  },
  {
    id: 6,
    name: "Shavkat Nasriddinov",
    username: "shavkat_loveguru",
    email: "shavkat@uzbekjson.uz",
    phone: "+998-97-111-22-33",
    website: "loveguru.uz",
    bio: "Har yurak sevishga loyiq 💘",
    city: "Xiva",
    profession: "Muhabbat maslahatchisi",
    hobbies: ["podcast", "psixologik kitoblar", "tabiat qo‘shig‘i"],
  },
  {
    id: 7,
    name: "Dilnoza Tursunova",
    username: "dilnoza_dil",
    email: "dilnoza@uzbekjson.uz",
    phone: "+998-98-222-33-44",
    website: "romantikdil.uz",
    bio: "Yuragimning har bir urishi — sevgi haqida 🎶",
    city: "Qo‘qon",
    profession: "Rassom",
    hobbies: ["akvarel", "romantik illyustratsiyalar", "parvoz kuzatish"],
  },
  {
    id: 8,
    name: "Jahongir Raufov",
    username: "jahon_sado",
    email: "jahongir@uzbekjson.uz",
    phone: "+998-93-555-66-77",
    website: "jahon_lover.uz",
    bio: "Muhabbatni gap bilan emas, jimlikda sezasiz 🌌",
    city: "Termiz",
    profession: "Ruhshunos",
    hobbies: ["fonarli kechalar", "she’r o‘qish", "ko‘z bilan ifoda"],
  },
  {
    id: 9,
    name: "Gulbahor Toshpulatova",
    username: "gul_romance",
    email: "gulbahor@uzbekjson.uz",
    phone: "+998-99-111-22-11",
    website: "gulbahor_uz.uz",
    bio: "Sevgi — bu gullar bilan yozilgan she’rdir 🌸",
    city: "Navoiy",
    profession: "Gul dizayneri",
    hobbies: [
      "guldasta yasash",
      "sham yorug‘ida choy ichish",
      "klassik musiqalar",
    ],
  },
  {
    id: 10,
    name: "Azizbek Soliyev",
    username: "aziz_sensiz",
    email: "azizbek@uzbekjson.uz",
    phone: "+998-94-444-55-66",
    website: "azizbekromantik.uz",
    bio: "Muhabbatga ishonish — bu jasorat 💎",
    city: "Urganch",
    profession: "Yozuvchi",
    hobbies: ["romantik hikoya", "tungi yulduzlar", "qog‘oz xatlar"],
  },

  // 10ta yana generatsiya qilinmoqda...
  {
    id: 11,
    name: "Maftuna Karimova",
    username: "maftuna_lover",
    email: "maftuna@uzbekjson.uz",
    phone: "+998-93-999-88-77",
    website: "maftuna-love.uz",
    bio: "Har tun muhabbat haqida o‘ylayman 🌙",
    city: "Toshkent",
    profession: "Shoira",
    hobbies: ["oyga qarab she’r yozish", "sekin musiqalar", "qora choy"],
  },
  {
    id: 12,
    name: "Miraziz Obidov",
    username: "miraziz_romantik",
    email: "miraziz@uzbekjson.uz",
    phone: "+998-97-777-66-55",
    website: "mirazizlove.uz",
    bio: "Sevgi — bu chin yurakdan bir qadamdir ❤️‍🔥",
    city: "Jizzax",
    profession: "Kompozitor",
    hobbies: ["musiqa yozish", "qo‘shiq matnlari", "tungi pianino"],
  },
  {
    id: 13,
    name: "Dilshoda Rasulova",
    username: "dilshoda_qalb",
    email: "dilshoda@uzbekjson.uz",
    phone: "+998-96-222-33-11",
    website: "dilshoda.uz",
    bio: "Yuragim qog‘oz, sevgi esa siyoh 🎨",
    city: "Zarafshon",
    profession: "Illyustrator",
    hobbies: ["grafika", "lovestory suratlar", "gul bosma"],
  },
  {
    id: 14,
    name: "Shohruh Qodirov",
    username: "shoh_qalbda",
    email: "shohruh@uzbekjson.uz",
    phone: "+998-95-000-11-22",
    website: "shohruhromantik.uz",
    bio: "So‘zsizlik ham ba'zida muhabbatdir 🔇❤️",
    city: "Qarshi",
    profession: "San'atshunos",
    hobbies: ["toshga rasmlar", "grafit yozuvlar", "kechqurun chill"],
  },
  {
    id: 15,
    name: "Mushtariy Rahmatova",
    username: "mushtariy_yulduz",
    email: "mushtariy@uzbekjson.uz",
    phone: "+998-91-876-54-32",
    website: "mushtariyyulduz.uz",
    bio: "Muhabbat — bu har oqshom kutishdir 🌠",
    city: "Sirdaryo",
    profession: "Filosof",
    hobbies: ["shamlar", "yulduzlar nomi", "ko‘ngil daftar"],
  },
  {
    id: 16,
    name: "Oybek Sattorov",
    username: "oybek_lovestory",
    email: "oybek@uzbekjson.uz",
    phone: "+998-90-333-22-11",
    website: "oybekstory.uz",
    bio: "Har yurak hikoyasini tinglashga tayyorman 📖",
    city: "Toshkent",
    profession: "Hikoyachi",
    hobbies: ["voqealar yozish", "ko‘ngil suhbatlari", "avtobusda ilhom"],
  },
  {
    id: 17,
    name: "Yasmina Usmonova",
    username: "yasmina_tuyg‘u",
    email: "yasmina@uzbekjson.uz",
    phone: "+998-93-456-78-98",
    website: "yasminaromantic.uz",
    bio: "Muhabbatni rasmlarda kuylayman 💖",
    city: "Andijon",
    profession: "Rassom",
    hobbies: ["gul rasm", "san’at tahlili", "yozgi ilhom"],
  },
  {
    id: 18,
    name: "Javlon Shukurov",
    username: "javlon_lover",
    email: "javlon@uzbekjson.uz",
    phone: "+998-97-333-22-00",
    website: "javlonlove.uz",
    bio: "Muhabbat hayotga rang beradi 🖌️",
    city: "Guliston",
    profession: "Grafik dizayner",
    hobbies: ["illustratsiya", "minimal art", "ranglar bilan o‘ynash"],
  },
  {
    id: 19,
    name: "Madina Vohidova",
    username: "madina_qalbda",
    email: "madina@uzbekjson.uz",
    phone: "+998-94-567-89-00",
    website: "madinaromantik.uz",
    bio: "Yuragim — muhabbatning bekati 🚉",
    city: "Denov",
    profession: "Shoira",
    hobbies: ["yozuv mashinasi", "dengizni tinglash", "tun o‘qishlari"],
  },
  {
    id: 20,
    name: "Farrux Nurmatov",
    username: "farrux_sado",
    email: "farrux@uzbekjson.uz",
    phone: "+998-92-234-56-78",
    website: "farruxromantik.uz",
    bio: "Muhabbatni so‘zsiz ifodalayman 🎼",
    city: "Nukus",
    profession: "Badiiy bastakor",
    hobbies: ["skripka chalish", "ohanglar yozish", "tabiatda ilhom olish"],
  },
];

const adventureUsers = [
  {
    id: 1,
    name: "Shahzod Nurmatov",
    username: "shahzod_explorer",
    email: "shahzod@uzbekjson.uz",
    phone: "+998-90-123-45-01",
    website: "shahzod-sarguzasht.uz",
    bio: "Sarguzashtga to‘la hayot izlayman! 🧭",
    city: "Toshkent",
    profession: "Sayohatchi",
    hobbies: ["tog‘larga chiqish", "dasturlash", "foto olish"],
  },
  {
    id: 2,
    name: "Lola G‘anieva",
    username: "lola_adventure",
    email: "lola@uzbekjson.uz",
    phone: "+998-91-234-56-02",
    website: "lola-sayohat.uz",
    bio: "Har kun yangi manzil! ✈️",
    city: "Samarqand",
    profession: "Sayohat bloggeri",
    hobbies: ["blog yozish", "madaniyat o‘rganish", "velosport"],
  },
  {
    id: 3,
    name: "Jasur Mardonov",
    username: "jasur_trekker",
    email: "jasur@uzbekjson.uz",
    phone: "+998-92-345-67-03",
    website: "jasur-trek.uz",
    bio: "Yo‘llar menga kuch beradi 🚶",
    city: "Andijon",
    profession: "Trekker",
    hobbies: ["tog‘ yurish", "suratga olish", "dron uchirish"],
  },
  {
    id: 4,
    name: "Diyora Xolmurodova",
    username: "diyora_nomad",
    email: "diyora@uzbekjson.uz",
    phone: "+998-93-456-78-04",
    website: "diyora-nomad.uz",
    bio: "Hayot yurishda go‘zal 👣",
    city: "Farg‘ona",
    profession: "Digital nomad",
    hobbies: ["kod yozish", "kamp qilish", "mahalliy ovqatlar"],
  },
  {
    id: 5,
    name: "Ulug‘bek Raxmonov",
    username: "ulugbek_pathfinder",
    email: "ulugbek@uzbekjson.uz",
    phone: "+998-94-567-89-05",
    website: "ulugbek-path.uz",
    bio: "Xarita — mening do‘stim 🗺️",
    city: "Buxoro",
    profession: "Yo‘lchi",
    hobbies: ["sayr qilish", "qadimiy joylar", "hikoya yozish"],
  },
  {
    id: 6,
    name: "Dilnoza Eshqobilova",
    username: "dilnoza_mountain",
    email: "dilnoza@uzbekjson.uz",
    phone: "+998-95-678-90-06",
    website: "dilnoza-tabiat.uz",
    bio: "Tabiat yuragimni tinchlantiradi 🌿",
    city: "Namangan",
    profession: "Eko-sayohatchi",
    hobbies: ["yovvoyi tabiat", "qush kuzatuv", "tabiat blogi"],
  },
  {
    id: 7,
    name: "Baxtiyor Tursunov",
    username: "baxtiyor_rover",
    email: "baxtiyor@uzbekjson.uz",
    phone: "+998-96-789-01-07",
    website: "baxtiyor-rover.uz",
    bio: "Sarguzashtsiz hayot - zerikarlidir 🚙",
    city: "Qarshi",
    profession: "Offroad haydovchisi",
    hobbies: ["avtomobil sayohati", "texnika", "qumloqda yurish"],
  },
  {
    id: 8,
    name: "Sevinch Yusupova",
    username: "sevinch_travel",
    email: "sevinch@uzbekjson.uz",
    phone: "+998-97-890-12-08",
    website: "sevinch-dunyo.uz",
    bio: "Har bir yurtda yangi hikoya bor 📖",
    city: "Navoiy",
    profession: "Geograf",
    hobbies: ["madaniyat", "yurtlar tarixi", "eskiz chizish"],
  },
  {
    id: 9,
    name: "Sherzod Xudoyberdiyev",
    username: "sherzod_hiker",
    email: "sherzod@uzbekjson.uz",
    phone: "+998-98-901-23-09",
    website: "sherzod-hike.uz",
    bio: "Qadamlarimni tog‘lar sevadi ⛰️",
    city: "Xorazm",
    profession: "Tog‘ yuruvchisi",
    hobbies: ["tog‘ yurish", "foto olam", "mushohada"],
  },
  {
    id: 10,
    name: "Ozoda Qo‘chqarova",
    username: "ozoda_cyclist",
    email: "ozoda@uzbekjson.uz",
    phone: "+998-99-012-34-10",
    website: "ozoda-bike.uz",
    bio: "Hayot yo‘llarda davom etadi 🚴‍♀️",
    city: "Jizzax",
    profession: "Velosportchi",
    hobbies: ["velosipedda yurish", "video blog", "sport turmush"],
  },
  // 10 ta foydalanuvchi qo‘shamiz yana
  {
    id: 11,
    name: "Rustam Qodirov",
    username: "rustam_wanderer",
    email: "rustam@uzbekjson.uz",
    phone: "+998-90-111-11-11",
    website: "rustam-yo‘llarda.uz",
    bio: "Yo‘ldan to‘xtama, o‘zingni topasan 🔍",
    city: "Toshkent",
    profession: "Mustaqil sayohatchi",
    hobbies: ["yo‘lsizlik", "kitoblar", "intervyu olish"],
  },
  {
    id: 12,
    name: "Muqaddas Aliyeva",
    username: "muqaddas_tourist",
    email: "muqaddas@uzbekjson.uz",
    phone: "+998-91-222-22-12",
    website: "muqaddas-tour.uz",
    bio: "Har bir safar yangi esdaliklar demak 📸",
    city: "Sirdaryo",
    profession: "Turist",
    hobbies: ["galereya", "tarixiy joylar", "suhbatlar"],
  },
  {
    id: 13,
    name: "Komron Jo‘rayev",
    username: "komron_nomadlife",
    email: "komron@uzbekjson.uz",
    phone: "+998-92-333-33-13",
    website: "komron-nomad.uz",
    bio: "Ko‘chmanchi hayot menga mos 🏕️",
    city: "Termiz",
    profession: "Ko‘chmanchi dizayner",
    hobbies: ["dizayn", "ko‘chmanchilik", "sayr"],
  },
  {
    id: 14,
    name: "Mohira Eshonqulova",
    username: "mohira_camper",
    email: "mohira@uzbekjson.uz",
    phone: "+998-93-444-44-14",
    website: "mohira-camp.uz",
    bio: "Tabiat quchog‘ida erkinlik topaman 🍃",
    city: "Guliston",
    profession: "Kemper haydovchisi",
    hobbies: ["daraxt ostida dam olish", "kitob o‘qish", "choy ichish"],
  },
  {
    id: 15,
    name: "Zafar Shamsiyev",
    username: "zafar_backpacker",
    email: "zafar@uzbekjson.uz",
    phone: "+998-94-555-55-15",
    website: "zafar-backpack.uz",
    bio: "Yelkada sumka, yurakda orzu 🎒",
    city: "Denov",
    profession: "Backpacker",
    hobbies: ["oraliq joylar", "arzon sayohat", "san’at"],
  },
  {
    id: 16,
    name: "Nozima Asqarova",
    username: "nozima_explorer",
    email: "nozima@uzbekjson.uz",
    phone: "+998-95-666-66-16",
    website: "nozima-explore.uz",
    bio: "Dunyo — meniki, izlanish — yo‘lim 🌍",
    city: "Qo‘qon",
    profession: "Tadqiqotchi",
    hobbies: ["arxiv", "fotografiya", "podcast"],
  },
  {
    id: 17,
    name: "Iskandar Toshpo‘latov",
    username: "iskandar_trail",
    email: "iskandar@uzbekjson.uz",
    phone: "+998-96-777-77-17",
    website: "iskandar-trail.uz",
    bio: "Oyoq izlarim tarix bitadi 👣",
    city: "Chirchiq",
    profession: "Piyoda sayohatchi",
    hobbies: ["yo‘l yurish", "piyoda marafon", "suhbat"],
  },
  {
    id: 18,
    name: "Zilola Mirzayeva",
    username: "zilola_eco",
    email: "zilola@uzbekjson.uz",
    phone: "+998-97-888-88-18",
    website: "zilola-eko.uz",
    bio: "Ekoturizm — kelajak sari yo‘l 🏞️",
    city: "Urganch",
    profession: "Eko-gid",
    hobbies: ["eko loyihalar", "dasturlash", "kitoblar"],
  },
  {
    id: 19,
    name: "Farhod Sodiqov",
    username: "farhod_wilderness",
    email: "farhod@uzbekjson.uz",
    phone: "+998-98-999-99-19",
    website: "farhod-wild.uz",
    bio: "Yovvoyi tabiatda yashash san’ati 🦅",
    city: "Zarafshon",
    profession: "Tabiatshunos",
    hobbies: ["biologiya", "sayr", "qalam bilan yozish"],
  },
  {
    id: 20,
    name: "Gulbahor Muminova",
    username: "gulbahor_path",
    email: "gulbahor@uzbekjson.uz",
    phone: "+998-99-000-00-20",
    website: "gulbahor-path.uz",
    bio: "Qadamlarim orzular sari yetaklaydi ✨",
    city: "Xiva",
    profession: "Yo‘l tadqiqotchisi",
    hobbies: ["xarita tuzish", "eskizlar", "fotografiya"],
  },
];

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const style = searchParams.get("style") || "comedy";
  const id = searchParams.get("id");

  
  let users;
  switch (style) {
    case "comedy":
      users = comedyUsers;
      break;
    case "drama":
      users = dramaUsers;
      break;

    case "romance":
      users = romanceUsers;
      break;
    case "adventure":
      users = adventureUsers;
      break;
    default:
      users = comedyUsers;
  }

  if (id) {
    const user = users.find((u) => u.id === Number.parseInt(id));
    return NextResponse.json(user || null);
  }

  return NextResponse.json(users);
}
